### ISSUE TITLE
ribbon client crash

### ISSUE THREAD

**Issue by vaniron** [LypakasLobby/PokemonMythology#1]
Hi, getting this error and client crash after clicking on ribbon button in pokemon summary, happens only on Mythic mons:
https://pastebin.com/raw/pc6b96rs

**Comment by Lypaka-Dev** [comment]
https://gyazo.com/c39c3ac39d0d3753c9025bdaa0f51a75

Waiting to hear back on this rather interesting (to put it politely) situation.

**Comment by vaniron** [comment]
No idea whats going on there (i am really java beginner) but one of plugins we are using has prefix set like this and its working fine.
![image](https://github.com/LypakasLobby/PokemonMythology/assets/17107410/409b71ad-5e64-4366-b35d-375c4bba1eff)

So i guess its maybe due to usage of more advanced formatting in your case?

**Comment by vaniron** [comment]
I have added you to our repo so you can check it whole. I am not the original author so hard to explain anything.

**Comment by Lypaka-Dev** [comment]
Looks like Clover's shadow mod.

**Comment by vaniron** [comment]
Yes it is, just with few minor tweaks and translation. The point is the ribbons are working there.

**Comment by Lypaka-Dev** [comment]
He adds his own ribbons, like he creates new ones, if I'm not mistaken. Have you tried loading up your server without his mod installed now that its been loaded up with his mod?

**Comment by vaniron** [comment]
Yup thats true, well atleast some possible solution. Better than nothing. But i dont really care about clicking the ribbon in summary, i think most players doesnt care either. Was just wondering whats the matter so thanks for explaining its api bug.

**Comment by Lypaka-Dev** [comment]
Last I heard, removing Clover's mod from the server completely breaks Pokemon storage (like players lose all Pokemon) due to the Ribbon registry being unable to find his now-null Ribbon, and Pixelmon was too lazy to fix it with a simple try/catch, labeling it a server owner issue and that the Ribbons were working as intended. If Clover fixed that issue - or if Pixelmon miraculously did - I wouldn't mind referencing how his Ribbons work but until that time it looks like the summary is just gonna have to be broken. However, I did notice the setTitle() method in use in that code that I'm not using in mine so I'll give that a go here in a minute.

**Comment by vaniron** [comment]
I see, will try messing with Clovers mod on test server in few hours after work and report back with results.

**Comment by Lypaka-Dev** [comment]
https://gyazo.com/e94482a957dda055ef49ec9b4e3cc7a6

Daniel helped me fix it.

**Comment by Lypaka-Dev** [comment]
Can you reach out to me in my Discord so I know which one you are? I have a jar that fixes NEW Ribbons, but I need to check if OLD Ribbons are being properly updated to the fixed format and I don't have any Pokemon on me in my test world with the old Ribbon format.

**Comment by vaniron** [comment]
Fixed in 2.0.
